Description: >
  This template creates and verifies all the top level SSL certificates used throughout our services.

Parameters:
  Domain:
    Type: String
    Description: The domain we're registering the SSL cert for

  AltDomains:
    Type: String
    Description: The comma separated alternate domain names we're registering the SSL cert for
    Default: ''

  HostedZone:
    Type: String
    Description: The ID fo the hosted zone to use for SSL validation

Resources:
  TopLevelSSL:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref Domain
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: !Ref Domain
          HostedZoneId: !Ref HostedZone
      SubjectAlternativeNames:
        [!Sub '*.${Domain}', !Split [',', !Ref AltDomains]]

Outputs:
  SSLCert:
    Description: The ARN of the SSL cert zone for the requested Domain
    Value: !Ref TopLevelSSL
