Description: >
  These are the DNS entries that serve the core SuperGuard API

Parameters:
  EnvironmentName:
    Type: String
    Description: The name of the environment to add these entries to

  Domain:
    Type: String
    Description: The DNS name to add

  AllSubdomains:
    Type: String
    AllowedValues:
      - 'true'
      - 'false'
    Description: If true, will add a record to map all the subdomains to the ALB in addition to the top level domain
    Default: 'false'

Conditions:
  ShouldAddWildcardSubdomains: !Equals
    - !Ref AllSubdomains
    - 'true'

Resources:
  Record:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId: !ImportValue SuperGuardHostedZone
      RecordSets:
        - Name: !Ref Domain
          Type: A
          AliasTarget:
            DNSName:
              Fn::ImportValue: !Sub ${EnvironmentName}:PublicLoadBalancerUrl
            HostedZoneId:
              Fn::ImportValue: !Sub ${EnvironmentName}:PublicLoadBalancerHostedZone

  WildcardRecord:
    Type: AWS::Route53::RecordSetGroup
    Condition: ShouldAddWildcardSubdomains
    Properties:
      HostedZoneId: !ImportValue SuperGuardHostedZone
      RecordSets:
        - Name: !Sub '*.${Domain}'
          Type: A
          AliasTarget:
            DNSName:
              Fn::ImportValue: !Sub ${EnvironmentName}:PublicLoadBalancerUrl
            HostedZoneId:
              Fn::ImportValue: !Sub ${EnvironmentName}:PublicLoadBalancerHostedZone
