Description: >
  This template deploys an Image Repository

Parameters:
  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String

  RepoName:
    Description: A unique name for the ECR repo
    Type: String

Resources:
  ImageRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub '${RepoName}-${EnvironmentName}'

Outputs:
  ImageRepository:
    Description: A reference to the created repo
    Value: !Ref ImageRepository
