Description: >

  This template deploys a highly available ECS cluster using an AutoScaling Group, with 
  ECS hosts distributed across multiple Availability Zones.

  Last Modified: 4th November 2021
  Author: Varshneya Rao <varshneya.rao@toptal.com> (Original - Paul Maddox <pmaddox@amazon.com>)

Parameters:
  EnvironmentName:
    Type: String
    Default: production
    Description: The name of the environment this stack is being deployed for

  S3Bucket:
    Type: String
    Description: Please provide the S3 Bucket to find the Cloudformation yaml files
    Default: superguard-ecs-cloudformation

  S3Region:
    Type: String
    Description: Please provide the S3 region hosting the S3 bucket
    Default: ap-southeast-2

Resources:
  APIRepo:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${S3Bucket}.s3.${S3Region}.amazonaws.com/service/image-repo.yaml
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        RepoName: github-actions

  ECS:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${S3Bucket}.s3.${S3Region}.amazonaws.com/service/ecs-cluster.yaml
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        ClusterName: known-hosts
        InstanceType: t2.medium
        ClusterSize: 1
        MaxClusterSize: 4
        Subnets:
          Fn::ImportValue: !Sub ${EnvironmentName}:PrivateSubnets
        SecurityGroup:
          Fn::ImportValue: !Sub ${EnvironmentName}:ECSHostSecurityGroup

  LifecycleHook:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${S3Bucket}.s3.${S3Region}.amazonaws.com/service/lifecyclehook.yaml
      Parameters:
        Cluster: !GetAtt ECS.Outputs.Cluster
        ECSAutoScalingGroupName: !GetAtt ECS.Outputs.ECSAutoScalingGroupName

Outputs:
  ECSCluster:
    Description: The ECS Cluster ID that services should run on
    Value: !GetAtt ECS.Outputs.Cluster
    Export:
      Name: !Sub ${EnvironmentName}:ECSCluster

  ECSServiceAutoScalingRoleARN:
    Description: The ECS service auto scaling role ARN
    Value: !GetAtt ECS.Outputs.ECSServiceAutoScalingRole
    Export:
      Name: !Sub ${EnvironmentName}:ECSServiceAutoScalingRoleARN
